// backend/src/models/Workspace.js
import mongoose from 'mongoose';
import * as crypto from 'crypto';

const { Schema, model } = mongoose;

/**
 * Workspace schema represents a collaborative space where users can work together.
 */
const workspaceSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
      minlength: 3,
      maxlength: 100,
    },
    description: {
      type: String,
      trim: true,
      maxlength: 500,
    },
    owner: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    members: [
      {
        user: {
          type: Schema.Types.ObjectId,
          ref: 'User',
          required: true,
        },
        role: {
          type: String,
          enum: ['owner', 'admin', 'member'],
          default: 'member',
        },
      }
    ],
    // Must match exactly eight hexadecimal characters (/^[0-9a-fA-F]{8}$/)
    // Default value is generated by crypto.randomBytes(4).toString('hex'), giving you a random 8-character hex code
    inviteCode: {
      type: String,
      unique: true,
      match: /^[0-9a-fA-F]{8}$/,
      default: () => crypto.randomBytes(4).toString('hex')
    }
  },
  {
    timestamps: true, // adds createdAt and updatedAt
  }
);

// Index for quick lookup by name
workspaceSchema.index({ name: 1 });

const Workspace = model('Workspace', workspaceSchema);
export default Workspace;
